### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by cristianrz** [dylanaraps/pfetch#54] opened 2020-04-25 17:08 UTC
Tried running `pfetch` on [Windows with busybox](https://frippery.org/busybox/) and says "Windows_NT" not supported. Can we add it?

**Comment by dylanaraps** [comment] 2020-04-26 06:10
Yeah. There's only WSL/WSL2 support currently.

**Comment by dylanaraps** [comment] 2021-09-04 17:10
Closing as duplicate of https://github.com/dylanaraps/pfetch/issues/10

**Closed by dylanaraps** 2021-09-04 17:10 UTC
