### ISSUE TITLE
Double new line after palette

### ISSUE THREAD

**Issue by jasontheiler** [dylanaraps/pfetch#93] opened 2020-12-16 14:07 UTC
Hi!

I've set up pfetch as my fish greeting with the `fish_greeting` function and customized the shown infos to be:

`set -x PF_INFO ascii title os kernel uptime pkgs memory shell palette`

pfetch prints a new line at the end by default, but with `palette` enabled it draws two new lines at the end.

**Is this intended behaviour?**

'Cause I think it doesn't look that good this way. Especially with the new line that [Starship](https://starship.rs/) prints by default before the prompt (which I don't want to disable).

![pfetch_new_lines](https://user-images.githubusercontent.com/50220557/102358453-ce6cde00-3faf-11eb-8ea9-8871cbb08e98.png)

**Comment by SupremMotu** [comment] 2021-01-13 20:23
I can confirm the same thing happens for me on Arch Linux.

**Comment by TheThunderGuyS** [comment] 2021-05-03 14:52
I just created a [simple patch in my own fork](https://github.com/TheThunderGuyS/pfetch/tree/no-space-palette) that removes the second newline leaving only the first one, as well as removing the newline before the palette. You can `git apply` this diff on your local repo:

```
diff --git a/pfetch b/pfetch
index 039a898..9d350a1 100755
--- a/pfetch
+++ b/pfetch
@@ -1038,10 +1038,8 @@ get_palette() {
         palette="$palette$e"
     }
 
-    # Print the palette with a new-line before and afterwards.
-    printf '\n' >&6
-    log "$palette
-        " " " >&6
+    # Print the palette.
+    log "$palette" " " >&6
 }
 
 get_ascii() {
```

As indicated by the comments, the newlines are intended behavior and I don't see my patch being merged any time soon.

**Closed** 2021-09-08 00:31 UTC
